### ISSUE TITLE
Incorrect behaviour when using queryset based on another queryset

### ISSUE THREAD

**Issue by sh4r3m4n** [charles-vdulac/django-roa#25]
Pasting IPython output
In [92]: # Normal queryset
In [93]: qs = User.objects.all()

In [94]: another_qs = qs.filter(pk=1)

In [95]: qs is another_qs
Out[95]: False

In [96]: another_qs # Only the filtered ones
Out[96]: [User: user1]

In [97]: qs # Should display all users
Out[97]: [User: user1, User: user2, User: user3, User: user4]

In [98]: # Queryset using ROA
In [99]: qs = SomeRoaModel.objects.all()

In [100]: another_qs = qs.filter(pk=1)

In [101]: qs is another_qs
Out[101]: False

In [102]: another_qs # Only the filtered ones
Out[102]: [SomeRoaModel: AAA]

In [103]: qs # Should display all objects (AAA, BBB, CCC and DDD)
Out[103]: [SomeRoaModel: AAA] <-- It shows only the another_qs' objects instead of the qs ones

This problem is breaking the validation of a ROAModel in my admin site, how can it be solved?

**Comment by sh4r3m4n** [comment]
I made a patch to make this work properly: https://github.com/sh4r3m4n/django-roa/commit/4b829a74b656b1638f62971685836ed7b9d289d9

**Comment by charles-vdulac** [comment]
I've just merged it. Thanks !
